name: Mirror to basetrustlayer-cmd

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to mirror
        env:
          MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          git config --global user.email "mirror@whisperm.io"
          git config --global user.name "WhispeRM Mirror"
          git remote add mirror https://basetrustlayer-cmd:${MIRROR_TOKEN}@github.com/basetrustlayer-cmd/whisperm.git
          git push mirror main --force
